### PR TITLE
added dis paper

### PR DESCRIPTION
**Pull request by jesscs**

### CODE REVIEW

**Comment by jayfo** [comment]
Unfortunately I don't think that's a very good thumbnail.  Would be better if cropped to either of the images, rather than whiteboxing around both of them?

**Comment by jesscs** [comment]
None of my tools are letting me resize right. I can send you a square image
of the calendar and you can see if you can make it the right size? It was
so blurry when I tried that I figured it was better to have something that
was at least recognizable from the paper itself :-/

**Comment by karkar** [comment]
I can do it if you give explicit instructions on what to do.
p.s. overlapping works if you don't care about obstructing information.

**Comment by jayfo** [comment]
Interesting.  Send me the source image via email?

**Comment by jayfo** [comment]
So apparently I have a test that ensures thumbs are 120x120.  Damnit me.  😆 

Today is not the day I'm switching all the thumbs down to 100x100, which I should do to match CHI.  But I had thumbs before CHI did, damnit.

Can you make a 120x120?  Either by cropping differently or scaling differently?

**Pull request merged**
