### PR TITLE
Ubi16 cameraready update

### PR DESCRIPTION
**Pull request by depstein**
When things break, make a new branch and try again!

### CODE REVIEW

**Comment by jayfo** [comment]
Now it looks the same as before.

I think your `master` is messed.

```
git checkout master
git reset --hard fogies/master
git checkout <branch>
git rebase master
```

**Comment by depstein** [comment]
That didn't seem to do much.

My master is even with yours, but I'm generating a bunch of merge commits? Probably something related to me being lazy and using the GUI.

**Comment by jayfo** [comment]
Since you replaced the PDF in the second commit, you're now adding two PDFs to the history, one of which we don't need.  The second commit was a fix, which we should get rid of.

```
git rebase -i master
```

Reword the first, give it a meaningful commit message.

Mark the second commit as a fix, it'll get merged into the first.

```
git push -f
```

**Comment by depstein** [comment]
I think I'm making it worse.

**Comment by jayfo** [comment]
Indeed. That's impressive. I have no idea how you managed that.

Did you issue a `pull` along the way or something?

Can you `rebase -i master`, drop all the commits you don't want (i.e., by deleting their line)?

**Comment by depstein** [comment]
Yeah, I must have `pull`ed. It's clean now though, and that PDF is the right one.

**Pull request merged**
