### PR TITLE
Ubi16 cameraready

### PR DESCRIPTION
**Pull request by depstein**

### CODE REVIEW

**Comment by jayfo** [comment]
You seem to be based on some weird old branch.

Can you rebase this onto master?

```
git checkout master
git pull fogies master
git push
git check <branch>
git rebase master
```

**Comment by depstein** [comment]
Did that do the thing?

**Comment by jayfo** [comment]
That somehow made it worse.

**Comment by depstein** [comment]
Screw it, I'll do it in a new branch.

**Pull request closed without merging**
