### PR TITLE
fixing image size for cscw paper

### PR DESCRIPTION
**Pull request by lrpina**

### CODE REVIEW

**Comment by jayfo** [comment]
But now things are all distorted and weird looking?

**Comment by lrpina** [comment]
yeah! it looks weird now!

**Comment by jayfo** [comment]
Yeah.  Either crop it so that it's not distorted, or find a different image.

If you crop, maybe trim from both sides, so nobody gets maimed.

**Comment by jayfo** [comment]
I did a quick search on noun project, trying to avoid depictions that were too stereotypical, and seeking depictions that included / foregrounded children.

How about this:

https://thenounproject.com/term/family/195451/

Alternatively:

https://thenounproject.com/term/family/42890/

https://thenounproject.com/term/family/92733/

https://thenounproject.com/term/family/150666/

**Comment by depstein** [comment]
Sorry to chime in. The noun project is great, but for something public-facing like this I wonder if you need to pay for the royalty-free version of the images?

Or is acknowledging the creator in the alt-text sufficient?

**Comment by jayfo** [comment]
Do people still pay for things in Trump's America?

I'd be fine grabbing fogies subscription at 9.99 per month.  We don't icon enough for a team.

Frankly, it'd probably be cheaper to pay only for those we use?

**Comment by depstein** [comment]
Haha!

The yearly rate is much cheaper, $30/yr... I think I use 15 icons a year in my slides alone. I would support a fogies license. I've been thinking lately that I want to make sure I have proper licenses for any images I use in a job talk, for example.

**Comment by lrpina** [comment]
Probably just paying for the one we use is fine.

**Comment by jayfo** [comment]
Where do you see yearly pricing?

https://thenounproject.com/accounts/pricing/

**Comment by lrpina** [comment]
I would support a license, but I'm not the one paying! :-)

**Comment by depstein** [comment]
I clicked an image link, went to download, followed "royalty free" option and got 3 choices: the same $9.99/month, $29.99/year, and $1.99 for the one icon.

It's worth ensuring it's not just a Comcast-type year 1 discount.

**Comment by jayfo** [comment]
Found it.  We have a fogies@cs NounProject subscription.

**Comment by jayfo** [comment]
Can you use this image, with a white background instead of transparent?

cscw2017-familyinformatics

**Comment by jayfo** [comment]
Then, your pull is failing the tests because of this (click on the red x above near `adc96d2`):

```
======================================================================
FAIL: Confirm all files references by a paper actually exist.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/fogies/web-jayfo/tests/test_conferencepapers.py", line 66, in test_conferencepapers_files_exist
    '{} references localthumb {} not found in publications/'.format(id_conferencepaper, file_path)
AssertionError: False is not true : id_conferencepaper_cscw2017_familyinformatics references localthumb cscw2017-familyinformatics.jpeg not found in publications/
```

The entry in the conferences files is referencing a jpeg that doesn't exist, instead of the png that does.

**Comment by jayfo** [comment]
Yay!

**Pull request merged**
