### PR TITLE
Added pages and official URL

### LINKED ISSUE #71: Fix UbiComp for Post-Publication

### PR DESCRIPTION
**Pull request by depstein**
Resolves #71.

### CODE REVIEW

**Comment by jayfo** [comment]
I'll merge this sooner if you rebase it on the current master, such that the build will pass.

**Comment by depstein** [comment]
Whoa, I did a git thing!

**Comment by jayfo** [comment]
Actually, you didn't.

**Comment by depstein** [comment]
Much confused. build is passing, no?

**Comment by jayfo** [comment]
You seem to have merged, not rebased. It'll be fine, but the result is a mess in the git history.

Decided I don't have time to care about that.  :)

**Pull request merged**
